services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"

    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=alphacon
      - DB_USER=user
      - DB_PASS=LOIJasd#6
    depends_on:
      - database
    command:
      sh -c "python manage.py runserver 0.0.0.0:8000"


  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=alphacon
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=LOIJasd#6

  redis:
    image: redis:7.0.5-alpine
    hostname: redis


  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

  nginx:
      image: nginx
      ports:
        - "80:80"
  #    volumes:
  #      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     # depends_on:
     #   - web-app
